### ISSUE TITLE
Multiselect with Ctrl+n, background is transparent? 

### ISSUE THREAD

**Issue by seriiserii825** [AlexvZyl/nordic.nvim#156]
Hi, thanks for theme, it's really cool.

When i select with ctrl+n in nordic
![nordic-select](https://github.com/user-attachments/assets/8e32ae68-eb25-4aa4-9762-49160f993e8b)

And onedark

![ondedark](https://github.com/user-attachments/assets/ba826cc8-7d00-4501-b62c-efea441d9e49)

**Comment by 5-pebbles** [comment]
I am assuming you are using vim-visual-multi, which we currently don't support. This weekend I will install the plugin and find the right highlight, if you would like to do it your self I think this is the related documentation:

https://github.com/mg979/vim-visual-multi/blob/a6975e7c1ee157615bbc80fc25e4392f71c344d4/doc/vm-settings.txt#L207


Also, for future reference, please include the name of the plugin you are using so maintainers don't have to search through your GitHub to find your config and then search through that to find what plugins you are using.

**Comment by seriiserii825** [comment]
Thank you

**Comment by 5-pebbles** [comment]
I have no idea what the issue is (was), but it is fixed in the `dev` branch.

update this [line]( https://github.com/seriiserii825/nvim-coc/blob/bed3462914f8244d23c438361fe7a1c26662bff6/plugins.vim#L19) in your config to the following:
```vim
Plug 'AlexvZyl/nordic.nvim', { 'branch': 'dev' }
```

It should be fixed on `main` with the next release (#144). After that I will close this issue assuming everything is still working.

**Comment by seriiserii825** [comment]
Thank you, used dev branch, and now it's highligted.

**Comment by AlexvZyl** [comment]
FYI dev got merged :)
